# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/duong/MediaPlayerApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/duong/MediaPlayerApp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duong/MediaPlayerApp/CMakeFiles /home/duong/MediaPlayerApp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/duong/MediaPlayerApp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MediaPlayerApp

# Build rule for target.
MediaPlayerApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MediaPlayerApp
.PHONY : MediaPlayerApp

# fast build rule for target.
MediaPlayerApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/build
.PHONY : MediaPlayerApp/fast

#=============================================================================
# Target rules for targets named RunTests

# Build rule for target.
RunTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RunTests
.PHONY : RunTests

# fast build rule for target.
RunTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/build
.PHONY : RunTests/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

src/config/AppConfig.o: src/config/AppConfig.cpp.o
.PHONY : src/config/AppConfig.o

# target to build an object file
src/config/AppConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/config/AppConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/config/AppConfig.cpp.o
.PHONY : src/config/AppConfig.cpp.o

src/config/AppConfig.i: src/config/AppConfig.cpp.i
.PHONY : src/config/AppConfig.i

# target to preprocess a source file
src/config/AppConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/config/AppConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/config/AppConfig.cpp.i
.PHONY : src/config/AppConfig.cpp.i

src/config/AppConfig.s: src/config/AppConfig.cpp.s
.PHONY : src/config/AppConfig.s

# target to generate assembly for a file
src/config/AppConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/config/AppConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/config/AppConfig.cpp.s
.PHONY : src/config/AppConfig.cpp.s

src/controllers/HardwareController.o: src/controllers/HardwareController.cpp.o
.PHONY : src/controllers/HardwareController.o

# target to build an object file
src/controllers/HardwareController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/HardwareController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/HardwareController.cpp.o
.PHONY : src/controllers/HardwareController.cpp.o

src/controllers/HardwareController.i: src/controllers/HardwareController.cpp.i
.PHONY : src/controllers/HardwareController.i

# target to preprocess a source file
src/controllers/HardwareController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/HardwareController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/HardwareController.cpp.i
.PHONY : src/controllers/HardwareController.cpp.i

src/controllers/HardwareController.s: src/controllers/HardwareController.cpp.s
.PHONY : src/controllers/HardwareController.s

# target to generate assembly for a file
src/controllers/HardwareController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/HardwareController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/HardwareController.cpp.s
.PHONY : src/controllers/HardwareController.cpp.s

src/controllers/LibraryController.o: src/controllers/LibraryController.cpp.o
.PHONY : src/controllers/LibraryController.o

# target to build an object file
src/controllers/LibraryController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/LibraryController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/LibraryController.cpp.o
.PHONY : src/controllers/LibraryController.cpp.o

src/controllers/LibraryController.i: src/controllers/LibraryController.cpp.i
.PHONY : src/controllers/LibraryController.i

# target to preprocess a source file
src/controllers/LibraryController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/LibraryController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/LibraryController.cpp.i
.PHONY : src/controllers/LibraryController.cpp.i

src/controllers/LibraryController.s: src/controllers/LibraryController.cpp.s
.PHONY : src/controllers/LibraryController.s

# target to generate assembly for a file
src/controllers/LibraryController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/LibraryController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/LibraryController.cpp.s
.PHONY : src/controllers/LibraryController.cpp.s

src/controllers/MainController.o: src/controllers/MainController.cpp.o
.PHONY : src/controllers/MainController.o

# target to build an object file
src/controllers/MainController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/MainController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/MainController.cpp.o
.PHONY : src/controllers/MainController.cpp.o

src/controllers/MainController.i: src/controllers/MainController.cpp.i
.PHONY : src/controllers/MainController.i

# target to preprocess a source file
src/controllers/MainController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/MainController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/MainController.cpp.i
.PHONY : src/controllers/MainController.cpp.i

src/controllers/MainController.s: src/controllers/MainController.cpp.s
.PHONY : src/controllers/MainController.s

# target to generate assembly for a file
src/controllers/MainController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/MainController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/MainController.cpp.s
.PHONY : src/controllers/MainController.cpp.s

src/controllers/PlaybackController.o: src/controllers/PlaybackController.cpp.o
.PHONY : src/controllers/PlaybackController.o

# target to build an object file
src/controllers/PlaybackController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/PlaybackController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/PlaybackController.cpp.o
.PHONY : src/controllers/PlaybackController.cpp.o

src/controllers/PlaybackController.i: src/controllers/PlaybackController.cpp.i
.PHONY : src/controllers/PlaybackController.i

# target to preprocess a source file
src/controllers/PlaybackController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/PlaybackController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/PlaybackController.cpp.i
.PHONY : src/controllers/PlaybackController.cpp.i

src/controllers/PlaybackController.s: src/controllers/PlaybackController.cpp.s
.PHONY : src/controllers/PlaybackController.s

# target to generate assembly for a file
src/controllers/PlaybackController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/PlaybackController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/PlaybackController.cpp.s
.PHONY : src/controllers/PlaybackController.cpp.s

src/controllers/PlaylistController.o: src/controllers/PlaylistController.cpp.o
.PHONY : src/controllers/PlaylistController.o

# target to build an object file
src/controllers/PlaylistController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/PlaylistController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/PlaylistController.cpp.o
.PHONY : src/controllers/PlaylistController.cpp.o

src/controllers/PlaylistController.i: src/controllers/PlaylistController.cpp.i
.PHONY : src/controllers/PlaylistController.i

# target to preprocess a source file
src/controllers/PlaylistController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/PlaylistController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/PlaylistController.cpp.i
.PHONY : src/controllers/PlaylistController.cpp.i

src/controllers/PlaylistController.s: src/controllers/PlaylistController.cpp.s
.PHONY : src/controllers/PlaylistController.s

# target to generate assembly for a file
src/controllers/PlaylistController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/PlaylistController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/PlaylistController.cpp.s
.PHONY : src/controllers/PlaylistController.cpp.s

src/controllers/QueueController.o: src/controllers/QueueController.cpp.o
.PHONY : src/controllers/QueueController.o

# target to build an object file
src/controllers/QueueController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/QueueController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/QueueController.cpp.o
.PHONY : src/controllers/QueueController.cpp.o

src/controllers/QueueController.i: src/controllers/QueueController.cpp.i
.PHONY : src/controllers/QueueController.i

# target to preprocess a source file
src/controllers/QueueController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/QueueController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/QueueController.cpp.i
.PHONY : src/controllers/QueueController.cpp.i

src/controllers/QueueController.s: src/controllers/QueueController.cpp.s
.PHONY : src/controllers/QueueController.s

# target to generate assembly for a file
src/controllers/QueueController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/QueueController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/QueueController.cpp.s
.PHONY : src/controllers/QueueController.cpp.s

src/controllers/SourceController.o: src/controllers/SourceController.cpp.o
.PHONY : src/controllers/SourceController.o

# target to build an object file
src/controllers/SourceController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/SourceController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/SourceController.cpp.o
.PHONY : src/controllers/SourceController.cpp.o

src/controllers/SourceController.i: src/controllers/SourceController.cpp.i
.PHONY : src/controllers/SourceController.i

# target to preprocess a source file
src/controllers/SourceController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/SourceController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/SourceController.cpp.i
.PHONY : src/controllers/SourceController.cpp.i

src/controllers/SourceController.s: src/controllers/SourceController.cpp.s
.PHONY : src/controllers/SourceController.s

# target to generate assembly for a file
src/controllers/SourceController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/controllers/SourceController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/controllers/SourceController.cpp.s
.PHONY : src/controllers/SourceController.cpp.s

src/core/Application.o: src/core/Application.cpp.o
.PHONY : src/core/Application.o

# target to build an object file
src/core/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/core/Application.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/core/Application.cpp.o
.PHONY : src/core/Application.cpp.o

src/core/Application.i: src/core/Application.cpp.i
.PHONY : src/core/Application.i

# target to preprocess a source file
src/core/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/core/Application.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/core/Application.cpp.i
.PHONY : src/core/Application.cpp.i

src/core/Application.s: src/core/Application.cpp.s
.PHONY : src/core/Application.s

# target to generate assembly for a file
src/core/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/core/Application.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/core/Application.cpp.s
.PHONY : src/core/Application.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models/LibraryModel.o: src/models/LibraryModel.cpp.o
.PHONY : src/models/LibraryModel.o

# target to build an object file
src/models/LibraryModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/LibraryModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/LibraryModel.cpp.o
.PHONY : src/models/LibraryModel.cpp.o

src/models/LibraryModel.i: src/models/LibraryModel.cpp.i
.PHONY : src/models/LibraryModel.i

# target to preprocess a source file
src/models/LibraryModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/LibraryModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/LibraryModel.cpp.i
.PHONY : src/models/LibraryModel.cpp.i

src/models/LibraryModel.s: src/models/LibraryModel.cpp.s
.PHONY : src/models/LibraryModel.s

# target to generate assembly for a file
src/models/LibraryModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/LibraryModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/LibraryModel.cpp.s
.PHONY : src/models/LibraryModel.cpp.s

src/models/MediaFileModel.o: src/models/MediaFileModel.cpp.o
.PHONY : src/models/MediaFileModel.o

# target to build an object file
src/models/MediaFileModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/MediaFileModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/MediaFileModel.cpp.o
.PHONY : src/models/MediaFileModel.cpp.o

src/models/MediaFileModel.i: src/models/MediaFileModel.cpp.i
.PHONY : src/models/MediaFileModel.i

# target to preprocess a source file
src/models/MediaFileModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/MediaFileModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/MediaFileModel.cpp.i
.PHONY : src/models/MediaFileModel.cpp.i

src/models/MediaFileModel.s: src/models/MediaFileModel.cpp.s
.PHONY : src/models/MediaFileModel.s

# target to generate assembly for a file
src/models/MediaFileModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/MediaFileModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/MediaFileModel.cpp.s
.PHONY : src/models/MediaFileModel.cpp.s

src/models/MetadataModel.o: src/models/MetadataModel.cpp.o
.PHONY : src/models/MetadataModel.o

# target to build an object file
src/models/MetadataModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/MetadataModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/MetadataModel.cpp.o
.PHONY : src/models/MetadataModel.cpp.o

src/models/MetadataModel.i: src/models/MetadataModel.cpp.i
.PHONY : src/models/MetadataModel.i

# target to preprocess a source file
src/models/MetadataModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/MetadataModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/MetadataModel.cpp.i
.PHONY : src/models/MetadataModel.cpp.i

src/models/MetadataModel.s: src/models/MetadataModel.cpp.s
.PHONY : src/models/MetadataModel.s

# target to generate assembly for a file
src/models/MetadataModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/MetadataModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/MetadataModel.cpp.s
.PHONY : src/models/MetadataModel.cpp.s

src/models/PlaybackStateModel.o: src/models/PlaybackStateModel.cpp.o
.PHONY : src/models/PlaybackStateModel.o

# target to build an object file
src/models/PlaybackStateModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/PlaybackStateModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/PlaybackStateModel.cpp.o
.PHONY : src/models/PlaybackStateModel.cpp.o

src/models/PlaybackStateModel.i: src/models/PlaybackStateModel.cpp.i
.PHONY : src/models/PlaybackStateModel.i

# target to preprocess a source file
src/models/PlaybackStateModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/PlaybackStateModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/PlaybackStateModel.cpp.i
.PHONY : src/models/PlaybackStateModel.cpp.i

src/models/PlaybackStateModel.s: src/models/PlaybackStateModel.cpp.s
.PHONY : src/models/PlaybackStateModel.s

# target to generate assembly for a file
src/models/PlaybackStateModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/PlaybackStateModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/PlaybackStateModel.cpp.s
.PHONY : src/models/PlaybackStateModel.cpp.s

src/models/PlaylistModel.o: src/models/PlaylistModel.cpp.o
.PHONY : src/models/PlaylistModel.o

# target to build an object file
src/models/PlaylistModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/PlaylistModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/PlaylistModel.cpp.o
.PHONY : src/models/PlaylistModel.cpp.o

src/models/PlaylistModel.i: src/models/PlaylistModel.cpp.i
.PHONY : src/models/PlaylistModel.i

# target to preprocess a source file
src/models/PlaylistModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/PlaylistModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/PlaylistModel.cpp.i
.PHONY : src/models/PlaylistModel.cpp.i

src/models/PlaylistModel.s: src/models/PlaylistModel.cpp.s
.PHONY : src/models/PlaylistModel.s

# target to generate assembly for a file
src/models/PlaylistModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/PlaylistModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/PlaylistModel.cpp.s
.PHONY : src/models/PlaylistModel.cpp.s

src/models/QueueModel.o: src/models/QueueModel.cpp.o
.PHONY : src/models/QueueModel.o

# target to build an object file
src/models/QueueModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/QueueModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/QueueModel.cpp.o
.PHONY : src/models/QueueModel.cpp.o

src/models/QueueModel.i: src/models/QueueModel.cpp.i
.PHONY : src/models/QueueModel.i

# target to preprocess a source file
src/models/QueueModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/QueueModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/QueueModel.cpp.i
.PHONY : src/models/QueueModel.cpp.i

src/models/QueueModel.s: src/models/QueueModel.cpp.s
.PHONY : src/models/QueueModel.s

# target to generate assembly for a file
src/models/QueueModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/models/QueueModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/models/QueueModel.cpp.s
.PHONY : src/models/QueueModel.cpp.s

src/repositories/HistoryRepository.o: src/repositories/HistoryRepository.cpp.o
.PHONY : src/repositories/HistoryRepository.o

# target to build an object file
src/repositories/HistoryRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/HistoryRepository.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/HistoryRepository.cpp.o
.PHONY : src/repositories/HistoryRepository.cpp.o

src/repositories/HistoryRepository.i: src/repositories/HistoryRepository.cpp.i
.PHONY : src/repositories/HistoryRepository.i

# target to preprocess a source file
src/repositories/HistoryRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/HistoryRepository.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/HistoryRepository.cpp.i
.PHONY : src/repositories/HistoryRepository.cpp.i

src/repositories/HistoryRepository.s: src/repositories/HistoryRepository.cpp.s
.PHONY : src/repositories/HistoryRepository.s

# target to generate assembly for a file
src/repositories/HistoryRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/HistoryRepository.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/HistoryRepository.cpp.s
.PHONY : src/repositories/HistoryRepository.cpp.s

src/repositories/LibraryRepository.o: src/repositories/LibraryRepository.cpp.o
.PHONY : src/repositories/LibraryRepository.o

# target to build an object file
src/repositories/LibraryRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/LibraryRepository.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/LibraryRepository.cpp.o
.PHONY : src/repositories/LibraryRepository.cpp.o

src/repositories/LibraryRepository.i: src/repositories/LibraryRepository.cpp.i
.PHONY : src/repositories/LibraryRepository.i

# target to preprocess a source file
src/repositories/LibraryRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/LibraryRepository.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/LibraryRepository.cpp.i
.PHONY : src/repositories/LibraryRepository.cpp.i

src/repositories/LibraryRepository.s: src/repositories/LibraryRepository.cpp.s
.PHONY : src/repositories/LibraryRepository.s

# target to generate assembly for a file
src/repositories/LibraryRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/LibraryRepository.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/LibraryRepository.cpp.s
.PHONY : src/repositories/LibraryRepository.cpp.s

src/repositories/PlaylistRepository.o: src/repositories/PlaylistRepository.cpp.o
.PHONY : src/repositories/PlaylistRepository.o

# target to build an object file
src/repositories/PlaylistRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/PlaylistRepository.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/PlaylistRepository.cpp.o
.PHONY : src/repositories/PlaylistRepository.cpp.o

src/repositories/PlaylistRepository.i: src/repositories/PlaylistRepository.cpp.i
.PHONY : src/repositories/PlaylistRepository.i

# target to preprocess a source file
src/repositories/PlaylistRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/PlaylistRepository.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/PlaylistRepository.cpp.i
.PHONY : src/repositories/PlaylistRepository.cpp.i

src/repositories/PlaylistRepository.s: src/repositories/PlaylistRepository.cpp.s
.PHONY : src/repositories/PlaylistRepository.s

# target to generate assembly for a file
src/repositories/PlaylistRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/repositories/PlaylistRepository.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/repositories/PlaylistRepository.cpp.s
.PHONY : src/repositories/PlaylistRepository.cpp.s

src/services/AudioPlaybackEngine.o: src/services/AudioPlaybackEngine.cpp.o
.PHONY : src/services/AudioPlaybackEngine.o

# target to build an object file
src/services/AudioPlaybackEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/AudioPlaybackEngine.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/AudioPlaybackEngine.cpp.o
.PHONY : src/services/AudioPlaybackEngine.cpp.o

src/services/AudioPlaybackEngine.i: src/services/AudioPlaybackEngine.cpp.i
.PHONY : src/services/AudioPlaybackEngine.i

# target to preprocess a source file
src/services/AudioPlaybackEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/AudioPlaybackEngine.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/AudioPlaybackEngine.cpp.i
.PHONY : src/services/AudioPlaybackEngine.cpp.i

src/services/AudioPlaybackEngine.s: src/services/AudioPlaybackEngine.cpp.s
.PHONY : src/services/AudioPlaybackEngine.s

# target to generate assembly for a file
src/services/AudioPlaybackEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/AudioPlaybackEngine.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/AudioPlaybackEngine.cpp.s
.PHONY : src/services/AudioPlaybackEngine.cpp.s

src/services/FileScanner.o: src/services/FileScanner.cpp.o
.PHONY : src/services/FileScanner.o

# target to build an object file
src/services/FileScanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/FileScanner.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/FileScanner.cpp.o
.PHONY : src/services/FileScanner.cpp.o

src/services/FileScanner.i: src/services/FileScanner.cpp.i
.PHONY : src/services/FileScanner.i

# target to preprocess a source file
src/services/FileScanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/FileScanner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/FileScanner.cpp.i
.PHONY : src/services/FileScanner.cpp.i

src/services/FileScanner.s: src/services/FileScanner.cpp.s
.PHONY : src/services/FileScanner.s

# target to generate assembly for a file
src/services/FileScanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/FileScanner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/FileScanner.cpp.s
.PHONY : src/services/FileScanner.cpp.s

src/services/MetadataReader.o: src/services/MetadataReader.cpp.o
.PHONY : src/services/MetadataReader.o

# target to build an object file
src/services/MetadataReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/MetadataReader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/MetadataReader.cpp.o
.PHONY : src/services/MetadataReader.cpp.o

src/services/MetadataReader.i: src/services/MetadataReader.cpp.i
.PHONY : src/services/MetadataReader.i

# target to preprocess a source file
src/services/MetadataReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/MetadataReader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/MetadataReader.cpp.i
.PHONY : src/services/MetadataReader.cpp.i

src/services/MetadataReader.s: src/services/MetadataReader.cpp.s
.PHONY : src/services/MetadataReader.s

# target to generate assembly for a file
src/services/MetadataReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/MetadataReader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/MetadataReader.cpp.s
.PHONY : src/services/MetadataReader.cpp.s

src/services/SerialCommunication.o: src/services/SerialCommunication.cpp.o
.PHONY : src/services/SerialCommunication.o

# target to build an object file
src/services/SerialCommunication.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/SerialCommunication.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/SerialCommunication.cpp.o
.PHONY : src/services/SerialCommunication.cpp.o

src/services/SerialCommunication.i: src/services/SerialCommunication.cpp.i
.PHONY : src/services/SerialCommunication.i

# target to preprocess a source file
src/services/SerialCommunication.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/SerialCommunication.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/SerialCommunication.cpp.i
.PHONY : src/services/SerialCommunication.cpp.i

src/services/SerialCommunication.s: src/services/SerialCommunication.cpp.s
.PHONY : src/services/SerialCommunication.s

# target to generate assembly for a file
src/services/SerialCommunication.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/services/SerialCommunication.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/services/SerialCommunication.cpp.s
.PHONY : src/services/SerialCommunication.cpp.s

src/ui/ImGuiManager.o: src/ui/ImGuiManager.cpp.o
.PHONY : src/ui/ImGuiManager.o

# target to build an object file
src/ui/ImGuiManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/ui/ImGuiManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/ui/ImGuiManager.cpp.o
.PHONY : src/ui/ImGuiManager.cpp.o

src/ui/ImGuiManager.i: src/ui/ImGuiManager.cpp.i
.PHONY : src/ui/ImGuiManager.i

# target to preprocess a source file
src/ui/ImGuiManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/ui/ImGuiManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/ui/ImGuiManager.cpp.i
.PHONY : src/ui/ImGuiManager.cpp.i

src/ui/ImGuiManager.s: src/ui/ImGuiManager.cpp.s
.PHONY : src/ui/ImGuiManager.s

# target to generate assembly for a file
src/ui/ImGuiManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/ui/ImGuiManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/ui/ImGuiManager.cpp.s
.PHONY : src/ui/ImGuiManager.cpp.s

src/ui/UIManager.o: src/ui/UIManager.cpp.o
.PHONY : src/ui/UIManager.o

# target to build an object file
src/ui/UIManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/ui/UIManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/ui/UIManager.cpp.o
.PHONY : src/ui/UIManager.cpp.o

src/ui/UIManager.i: src/ui/UIManager.cpp.i
.PHONY : src/ui/UIManager.i

# target to preprocess a source file
src/ui/UIManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/ui/UIManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/ui/UIManager.cpp.i
.PHONY : src/ui/UIManager.cpp.i

src/ui/UIManager.s: src/ui/UIManager.cpp.s
.PHONY : src/ui/UIManager.s

# target to generate assembly for a file
src/ui/UIManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/ui/UIManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/ui/UIManager.cpp.s
.PHONY : src/ui/UIManager.cpp.s

src/views/HistoryScreen.o: src/views/HistoryScreen.cpp.o
.PHONY : src/views/HistoryScreen.o

# target to build an object file
src/views/HistoryScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/HistoryScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/HistoryScreen.cpp.o
.PHONY : src/views/HistoryScreen.cpp.o

src/views/HistoryScreen.i: src/views/HistoryScreen.cpp.i
.PHONY : src/views/HistoryScreen.i

# target to preprocess a source file
src/views/HistoryScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/HistoryScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/HistoryScreen.cpp.i
.PHONY : src/views/HistoryScreen.cpp.i

src/views/HistoryScreen.s: src/views/HistoryScreen.cpp.s
.PHONY : src/views/HistoryScreen.s

# target to generate assembly for a file
src/views/HistoryScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/HistoryScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/HistoryScreen.cpp.s
.PHONY : src/views/HistoryScreen.cpp.s

src/views/LibraryScreen.o: src/views/LibraryScreen.cpp.o
.PHONY : src/views/LibraryScreen.o

# target to build an object file
src/views/LibraryScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/LibraryScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/LibraryScreen.cpp.o
.PHONY : src/views/LibraryScreen.cpp.o

src/views/LibraryScreen.i: src/views/LibraryScreen.cpp.i
.PHONY : src/views/LibraryScreen.i

# target to preprocess a source file
src/views/LibraryScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/LibraryScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/LibraryScreen.cpp.i
.PHONY : src/views/LibraryScreen.cpp.i

src/views/LibraryScreen.s: src/views/LibraryScreen.cpp.s
.PHONY : src/views/LibraryScreen.s

# target to generate assembly for a file
src/views/LibraryScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/LibraryScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/LibraryScreen.cpp.s
.PHONY : src/views/LibraryScreen.cpp.s

src/views/MainScreen.o: src/views/MainScreen.cpp.o
.PHONY : src/views/MainScreen.o

# target to build an object file
src/views/MainScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/MainScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/MainScreen.cpp.o
.PHONY : src/views/MainScreen.cpp.o

src/views/MainScreen.i: src/views/MainScreen.cpp.i
.PHONY : src/views/MainScreen.i

# target to preprocess a source file
src/views/MainScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/MainScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/MainScreen.cpp.i
.PHONY : src/views/MainScreen.cpp.i

src/views/MainScreen.s: src/views/MainScreen.cpp.s
.PHONY : src/views/MainScreen.s

# target to generate assembly for a file
src/views/MainScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/MainScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/MainScreen.cpp.s
.PHONY : src/views/MainScreen.cpp.s

src/views/NowPlayingBar.o: src/views/NowPlayingBar.cpp.o
.PHONY : src/views/NowPlayingBar.o

# target to build an object file
src/views/NowPlayingBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/NowPlayingBar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/NowPlayingBar.cpp.o
.PHONY : src/views/NowPlayingBar.cpp.o

src/views/NowPlayingBar.i: src/views/NowPlayingBar.cpp.i
.PHONY : src/views/NowPlayingBar.i

# target to preprocess a source file
src/views/NowPlayingBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/NowPlayingBar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/NowPlayingBar.cpp.i
.PHONY : src/views/NowPlayingBar.cpp.i

src/views/NowPlayingBar.s: src/views/NowPlayingBar.cpp.s
.PHONY : src/views/NowPlayingBar.s

# target to generate assembly for a file
src/views/NowPlayingBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/NowPlayingBar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/NowPlayingBar.cpp.s
.PHONY : src/views/NowPlayingBar.cpp.s

src/views/PlaylistScreen.o: src/views/PlaylistScreen.cpp.o
.PHONY : src/views/PlaylistScreen.o

# target to build an object file
src/views/PlaylistScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/PlaylistScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/PlaylistScreen.cpp.o
.PHONY : src/views/PlaylistScreen.cpp.o

src/views/PlaylistScreen.i: src/views/PlaylistScreen.cpp.i
.PHONY : src/views/PlaylistScreen.i

# target to preprocess a source file
src/views/PlaylistScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/PlaylistScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/PlaylistScreen.cpp.i
.PHONY : src/views/PlaylistScreen.cpp.i

src/views/PlaylistScreen.s: src/views/PlaylistScreen.cpp.s
.PHONY : src/views/PlaylistScreen.s

# target to generate assembly for a file
src/views/PlaylistScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/PlaylistScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/PlaylistScreen.cpp.s
.PHONY : src/views/PlaylistScreen.cpp.s

src/views/QueuePanel.o: src/views/QueuePanel.cpp.o
.PHONY : src/views/QueuePanel.o

# target to build an object file
src/views/QueuePanel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/QueuePanel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/QueuePanel.cpp.o
.PHONY : src/views/QueuePanel.cpp.o

src/views/QueuePanel.i: src/views/QueuePanel.cpp.i
.PHONY : src/views/QueuePanel.i

# target to preprocess a source file
src/views/QueuePanel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/QueuePanel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/QueuePanel.cpp.i
.PHONY : src/views/QueuePanel.cpp.i

src/views/QueuePanel.s: src/views/QueuePanel.cpp.s
.PHONY : src/views/QueuePanel.s

# target to generate assembly for a file
src/views/QueuePanel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/QueuePanel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/QueuePanel.cpp.s
.PHONY : src/views/QueuePanel.cpp.s

src/views/ScanScreen.o: src/views/ScanScreen.cpp.o
.PHONY : src/views/ScanScreen.o

# target to build an object file
src/views/ScanScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/ScanScreen.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/ScanScreen.cpp.o
.PHONY : src/views/ScanScreen.cpp.o

src/views/ScanScreen.i: src/views/ScanScreen.cpp.i
.PHONY : src/views/ScanScreen.i

# target to preprocess a source file
src/views/ScanScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/ScanScreen.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/ScanScreen.cpp.i
.PHONY : src/views/ScanScreen.cpp.i

src/views/ScanScreen.s: src/views/ScanScreen.cpp.s
.PHONY : src/views/ScanScreen.s

# target to generate assembly for a file
src/views/ScanScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MediaPlayerApp.dir/build.make CMakeFiles/MediaPlayerApp.dir/src/views/ScanScreen.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/src/views/ScanScreen.cpp.s
.PHONY : src/views/ScanScreen.cpp.s

tests/controllers/HardwareControllerBufferTest.o: tests/controllers/HardwareControllerBufferTest.cpp.o
.PHONY : tests/controllers/HardwareControllerBufferTest.o

# target to build an object file
tests/controllers/HardwareControllerBufferTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerBufferTest.cpp.o
.PHONY : tests/controllers/HardwareControllerBufferTest.cpp.o

tests/controllers/HardwareControllerBufferTest.i: tests/controllers/HardwareControllerBufferTest.cpp.i
.PHONY : tests/controllers/HardwareControllerBufferTest.i

# target to preprocess a source file
tests/controllers/HardwareControllerBufferTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerBufferTest.cpp.i
.PHONY : tests/controllers/HardwareControllerBufferTest.cpp.i

tests/controllers/HardwareControllerBufferTest.s: tests/controllers/HardwareControllerBufferTest.cpp.s
.PHONY : tests/controllers/HardwareControllerBufferTest.s

# target to generate assembly for a file
tests/controllers/HardwareControllerBufferTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerBufferTest.cpp.s
.PHONY : tests/controllers/HardwareControllerBufferTest.cpp.s

tests/controllers/HardwareControllerInvalidTest.o: tests/controllers/HardwareControllerInvalidTest.cpp.o
.PHONY : tests/controllers/HardwareControllerInvalidTest.o

# target to build an object file
tests/controllers/HardwareControllerInvalidTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerInvalidTest.cpp.o
.PHONY : tests/controllers/HardwareControllerInvalidTest.cpp.o

tests/controllers/HardwareControllerInvalidTest.i: tests/controllers/HardwareControllerInvalidTest.cpp.i
.PHONY : tests/controllers/HardwareControllerInvalidTest.i

# target to preprocess a source file
tests/controllers/HardwareControllerInvalidTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerInvalidTest.cpp.i
.PHONY : tests/controllers/HardwareControllerInvalidTest.cpp.i

tests/controllers/HardwareControllerInvalidTest.s: tests/controllers/HardwareControllerInvalidTest.cpp.s
.PHONY : tests/controllers/HardwareControllerInvalidTest.s

# target to generate assembly for a file
tests/controllers/HardwareControllerInvalidTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerInvalidTest.cpp.s
.PHONY : tests/controllers/HardwareControllerInvalidTest.cpp.s

tests/controllers/HardwareControllerParseTest.o: tests/controllers/HardwareControllerParseTest.cpp.o
.PHONY : tests/controllers/HardwareControllerParseTest.o

# target to build an object file
tests/controllers/HardwareControllerParseTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerParseTest.cpp.o
.PHONY : tests/controllers/HardwareControllerParseTest.cpp.o

tests/controllers/HardwareControllerParseTest.i: tests/controllers/HardwareControllerParseTest.cpp.i
.PHONY : tests/controllers/HardwareControllerParseTest.i

# target to preprocess a source file
tests/controllers/HardwareControllerParseTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerParseTest.cpp.i
.PHONY : tests/controllers/HardwareControllerParseTest.cpp.i

tests/controllers/HardwareControllerParseTest.s: tests/controllers/HardwareControllerParseTest.cpp.s
.PHONY : tests/controllers/HardwareControllerParseTest.s

# target to generate assembly for a file
tests/controllers/HardwareControllerParseTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerParseTest.cpp.s
.PHONY : tests/controllers/HardwareControllerParseTest.cpp.s

tests/controllers/HardwareControllerRefreshTest.o: tests/controllers/HardwareControllerRefreshTest.cpp.o
.PHONY : tests/controllers/HardwareControllerRefreshTest.o

# target to build an object file
tests/controllers/HardwareControllerRefreshTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerRefreshTest.cpp.o
.PHONY : tests/controllers/HardwareControllerRefreshTest.cpp.o

tests/controllers/HardwareControllerRefreshTest.i: tests/controllers/HardwareControllerRefreshTest.cpp.i
.PHONY : tests/controllers/HardwareControllerRefreshTest.i

# target to preprocess a source file
tests/controllers/HardwareControllerRefreshTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerRefreshTest.cpp.i
.PHONY : tests/controllers/HardwareControllerRefreshTest.cpp.i

tests/controllers/HardwareControllerRefreshTest.s: tests/controllers/HardwareControllerRefreshTest.cpp.s
.PHONY : tests/controllers/HardwareControllerRefreshTest.s

# target to generate assembly for a file
tests/controllers/HardwareControllerRefreshTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerRefreshTest.cpp.s
.PHONY : tests/controllers/HardwareControllerRefreshTest.cpp.s

tests/controllers/HardwareControllerTest.o: tests/controllers/HardwareControllerTest.cpp.o
.PHONY : tests/controllers/HardwareControllerTest.o

# target to build an object file
tests/controllers/HardwareControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerTest.cpp.o
.PHONY : tests/controllers/HardwareControllerTest.cpp.o

tests/controllers/HardwareControllerTest.i: tests/controllers/HardwareControllerTest.cpp.i
.PHONY : tests/controllers/HardwareControllerTest.i

# target to preprocess a source file
tests/controllers/HardwareControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerTest.cpp.i
.PHONY : tests/controllers/HardwareControllerTest.cpp.i

tests/controllers/HardwareControllerTest.s: tests/controllers/HardwareControllerTest.cpp.s
.PHONY : tests/controllers/HardwareControllerTest.s

# target to generate assembly for a file
tests/controllers/HardwareControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/HardwareControllerTest.cpp.s
.PHONY : tests/controllers/HardwareControllerTest.cpp.s

tests/controllers/LibraryControllerExtraTest.o: tests/controllers/LibraryControllerExtraTest.cpp.o
.PHONY : tests/controllers/LibraryControllerExtraTest.o

# target to build an object file
tests/controllers/LibraryControllerExtraTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/LibraryControllerExtraTest.cpp.o
.PHONY : tests/controllers/LibraryControllerExtraTest.cpp.o

tests/controllers/LibraryControllerExtraTest.i: tests/controllers/LibraryControllerExtraTest.cpp.i
.PHONY : tests/controllers/LibraryControllerExtraTest.i

# target to preprocess a source file
tests/controllers/LibraryControllerExtraTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/LibraryControllerExtraTest.cpp.i
.PHONY : tests/controllers/LibraryControllerExtraTest.cpp.i

tests/controllers/LibraryControllerExtraTest.s: tests/controllers/LibraryControllerExtraTest.cpp.s
.PHONY : tests/controllers/LibraryControllerExtraTest.s

# target to generate assembly for a file
tests/controllers/LibraryControllerExtraTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/LibraryControllerExtraTest.cpp.s
.PHONY : tests/controllers/LibraryControllerExtraTest.cpp.s

tests/controllers/LibraryControllerTest.o: tests/controllers/LibraryControllerTest.cpp.o
.PHONY : tests/controllers/LibraryControllerTest.o

# target to build an object file
tests/controllers/LibraryControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/LibraryControllerTest.cpp.o
.PHONY : tests/controllers/LibraryControllerTest.cpp.o

tests/controllers/LibraryControllerTest.i: tests/controllers/LibraryControllerTest.cpp.i
.PHONY : tests/controllers/LibraryControllerTest.i

# target to preprocess a source file
tests/controllers/LibraryControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/LibraryControllerTest.cpp.i
.PHONY : tests/controllers/LibraryControllerTest.cpp.i

tests/controllers/LibraryControllerTest.s: tests/controllers/LibraryControllerTest.cpp.s
.PHONY : tests/controllers/LibraryControllerTest.s

# target to generate assembly for a file
tests/controllers/LibraryControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/LibraryControllerTest.cpp.s
.PHONY : tests/controllers/LibraryControllerTest.cpp.s

tests/controllers/MainControllerTest.o: tests/controllers/MainControllerTest.cpp.o
.PHONY : tests/controllers/MainControllerTest.o

# target to build an object file
tests/controllers/MainControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/MainControllerTest.cpp.o
.PHONY : tests/controllers/MainControllerTest.cpp.o

tests/controllers/MainControllerTest.i: tests/controllers/MainControllerTest.cpp.i
.PHONY : tests/controllers/MainControllerTest.i

# target to preprocess a source file
tests/controllers/MainControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/MainControllerTest.cpp.i
.PHONY : tests/controllers/MainControllerTest.cpp.i

tests/controllers/MainControllerTest.s: tests/controllers/MainControllerTest.cpp.s
.PHONY : tests/controllers/MainControllerTest.s

# target to generate assembly for a file
tests/controllers/MainControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/MainControllerTest.cpp.s
.PHONY : tests/controllers/MainControllerTest.cpp.s

tests/controllers/PlaybackControllerAdvancedTest.o: tests/controllers/PlaybackControllerAdvancedTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerAdvancedTest.o

# target to build an object file
tests/controllers/PlaybackControllerAdvancedTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerAdvancedTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerAdvancedTest.cpp.o

tests/controllers/PlaybackControllerAdvancedTest.i: tests/controllers/PlaybackControllerAdvancedTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerAdvancedTest.i

# target to preprocess a source file
tests/controllers/PlaybackControllerAdvancedTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerAdvancedTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerAdvancedTest.cpp.i

tests/controllers/PlaybackControllerAdvancedTest.s: tests/controllers/PlaybackControllerAdvancedTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerAdvancedTest.s

# target to generate assembly for a file
tests/controllers/PlaybackControllerAdvancedTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerAdvancedTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerAdvancedTest.cpp.s

tests/controllers/PlaybackControllerEngineTest.o: tests/controllers/PlaybackControllerEngineTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerEngineTest.o

# target to build an object file
tests/controllers/PlaybackControllerEngineTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerEngineTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerEngineTest.cpp.o

tests/controllers/PlaybackControllerEngineTest.i: tests/controllers/PlaybackControllerEngineTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerEngineTest.i

# target to preprocess a source file
tests/controllers/PlaybackControllerEngineTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerEngineTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerEngineTest.cpp.i

tests/controllers/PlaybackControllerEngineTest.s: tests/controllers/PlaybackControllerEngineTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerEngineTest.s

# target to generate assembly for a file
tests/controllers/PlaybackControllerEngineTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerEngineTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerEngineTest.cpp.s

tests/controllers/PlaybackControllerNavigationTest.o: tests/controllers/PlaybackControllerNavigationTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerNavigationTest.o

# target to build an object file
tests/controllers/PlaybackControllerNavigationTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerNavigationTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerNavigationTest.cpp.o

tests/controllers/PlaybackControllerNavigationTest.i: tests/controllers/PlaybackControllerNavigationTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerNavigationTest.i

# target to preprocess a source file
tests/controllers/PlaybackControllerNavigationTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerNavigationTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerNavigationTest.cpp.i

tests/controllers/PlaybackControllerNavigationTest.s: tests/controllers/PlaybackControllerNavigationTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerNavigationTest.s

# target to generate assembly for a file
tests/controllers/PlaybackControllerNavigationTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerNavigationTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerNavigationTest.cpp.s

tests/controllers/PlaybackControllerTest.o: tests/controllers/PlaybackControllerTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerTest.o

# target to build an object file
tests/controllers/PlaybackControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerTest.cpp.o
.PHONY : tests/controllers/PlaybackControllerTest.cpp.o

tests/controllers/PlaybackControllerTest.i: tests/controllers/PlaybackControllerTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerTest.i

# target to preprocess a source file
tests/controllers/PlaybackControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerTest.cpp.i
.PHONY : tests/controllers/PlaybackControllerTest.cpp.i

tests/controllers/PlaybackControllerTest.s: tests/controllers/PlaybackControllerTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerTest.s

# target to generate assembly for a file
tests/controllers/PlaybackControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaybackControllerTest.cpp.s
.PHONY : tests/controllers/PlaybackControllerTest.cpp.s

tests/controllers/PlaylistControllerTest.o: tests/controllers/PlaylistControllerTest.cpp.o
.PHONY : tests/controllers/PlaylistControllerTest.o

# target to build an object file
tests/controllers/PlaylistControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaylistControllerTest.cpp.o
.PHONY : tests/controllers/PlaylistControllerTest.cpp.o

tests/controllers/PlaylistControllerTest.i: tests/controllers/PlaylistControllerTest.cpp.i
.PHONY : tests/controllers/PlaylistControllerTest.i

# target to preprocess a source file
tests/controllers/PlaylistControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaylistControllerTest.cpp.i
.PHONY : tests/controllers/PlaylistControllerTest.cpp.i

tests/controllers/PlaylistControllerTest.s: tests/controllers/PlaylistControllerTest.cpp.s
.PHONY : tests/controllers/PlaylistControllerTest.s

# target to generate assembly for a file
tests/controllers/PlaylistControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/PlaylistControllerTest.cpp.s
.PHONY : tests/controllers/PlaylistControllerTest.cpp.s

tests/controllers/QueueControllerTest.o: tests/controllers/QueueControllerTest.cpp.o
.PHONY : tests/controllers/QueueControllerTest.o

# target to build an object file
tests/controllers/QueueControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/QueueControllerTest.cpp.o
.PHONY : tests/controllers/QueueControllerTest.cpp.o

tests/controllers/QueueControllerTest.i: tests/controllers/QueueControllerTest.cpp.i
.PHONY : tests/controllers/QueueControllerTest.i

# target to preprocess a source file
tests/controllers/QueueControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/QueueControllerTest.cpp.i
.PHONY : tests/controllers/QueueControllerTest.cpp.i

tests/controllers/QueueControllerTest.s: tests/controllers/QueueControllerTest.cpp.s
.PHONY : tests/controllers/QueueControllerTest.s

# target to generate assembly for a file
tests/controllers/QueueControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/QueueControllerTest.cpp.s
.PHONY : tests/controllers/QueueControllerTest.cpp.s

tests/controllers/SourceControllerExtraTest.o: tests/controllers/SourceControllerExtraTest.cpp.o
.PHONY : tests/controllers/SourceControllerExtraTest.o

# target to build an object file
tests/controllers/SourceControllerExtraTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/SourceControllerExtraTest.cpp.o
.PHONY : tests/controllers/SourceControllerExtraTest.cpp.o

tests/controllers/SourceControllerExtraTest.i: tests/controllers/SourceControllerExtraTest.cpp.i
.PHONY : tests/controllers/SourceControllerExtraTest.i

# target to preprocess a source file
tests/controllers/SourceControllerExtraTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/SourceControllerExtraTest.cpp.i
.PHONY : tests/controllers/SourceControllerExtraTest.cpp.i

tests/controllers/SourceControllerExtraTest.s: tests/controllers/SourceControllerExtraTest.cpp.s
.PHONY : tests/controllers/SourceControllerExtraTest.s

# target to generate assembly for a file
tests/controllers/SourceControllerExtraTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/SourceControllerExtraTest.cpp.s
.PHONY : tests/controllers/SourceControllerExtraTest.cpp.s

tests/controllers/SourceControllerTest.o: tests/controllers/SourceControllerTest.cpp.o
.PHONY : tests/controllers/SourceControllerTest.o

# target to build an object file
tests/controllers/SourceControllerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/SourceControllerTest.cpp.o
.PHONY : tests/controllers/SourceControllerTest.cpp.o

tests/controllers/SourceControllerTest.i: tests/controllers/SourceControllerTest.cpp.i
.PHONY : tests/controllers/SourceControllerTest.i

# target to preprocess a source file
tests/controllers/SourceControllerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/SourceControllerTest.cpp.i
.PHONY : tests/controllers/SourceControllerTest.cpp.i

tests/controllers/SourceControllerTest.s: tests/controllers/SourceControllerTest.cpp.s
.PHONY : tests/controllers/SourceControllerTest.s

# target to generate assembly for a file
tests/controllers/SourceControllerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/controllers/SourceControllerTest.cpp.s
.PHONY : tests/controllers/SourceControllerTest.cpp.s

tests/models/LibraryModelTest.o: tests/models/LibraryModelTest.cpp.o
.PHONY : tests/models/LibraryModelTest.o

# target to build an object file
tests/models/LibraryModelTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/LibraryModelTest.cpp.o
.PHONY : tests/models/LibraryModelTest.cpp.o

tests/models/LibraryModelTest.i: tests/models/LibraryModelTest.cpp.i
.PHONY : tests/models/LibraryModelTest.i

# target to preprocess a source file
tests/models/LibraryModelTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/LibraryModelTest.cpp.i
.PHONY : tests/models/LibraryModelTest.cpp.i

tests/models/LibraryModelTest.s: tests/models/LibraryModelTest.cpp.s
.PHONY : tests/models/LibraryModelTest.s

# target to generate assembly for a file
tests/models/LibraryModelTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/LibraryModelTest.cpp.s
.PHONY : tests/models/LibraryModelTest.cpp.s

tests/models/MediaFileModelTest.o: tests/models/MediaFileModelTest.cpp.o
.PHONY : tests/models/MediaFileModelTest.o

# target to build an object file
tests/models/MediaFileModelTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/MediaFileModelTest.cpp.o
.PHONY : tests/models/MediaFileModelTest.cpp.o

tests/models/MediaFileModelTest.i: tests/models/MediaFileModelTest.cpp.i
.PHONY : tests/models/MediaFileModelTest.i

# target to preprocess a source file
tests/models/MediaFileModelTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/MediaFileModelTest.cpp.i
.PHONY : tests/models/MediaFileModelTest.cpp.i

tests/models/MediaFileModelTest.s: tests/models/MediaFileModelTest.cpp.s
.PHONY : tests/models/MediaFileModelTest.s

# target to generate assembly for a file
tests/models/MediaFileModelTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/MediaFileModelTest.cpp.s
.PHONY : tests/models/MediaFileModelTest.cpp.s

tests/models/MetadataModelTest.o: tests/models/MetadataModelTest.cpp.o
.PHONY : tests/models/MetadataModelTest.o

# target to build an object file
tests/models/MetadataModelTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/MetadataModelTest.cpp.o
.PHONY : tests/models/MetadataModelTest.cpp.o

tests/models/MetadataModelTest.i: tests/models/MetadataModelTest.cpp.i
.PHONY : tests/models/MetadataModelTest.i

# target to preprocess a source file
tests/models/MetadataModelTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/MetadataModelTest.cpp.i
.PHONY : tests/models/MetadataModelTest.cpp.i

tests/models/MetadataModelTest.s: tests/models/MetadataModelTest.cpp.s
.PHONY : tests/models/MetadataModelTest.s

# target to generate assembly for a file
tests/models/MetadataModelTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/MetadataModelTest.cpp.s
.PHONY : tests/models/MetadataModelTest.cpp.s

tests/models/PlaybackStateModelTest.o: tests/models/PlaybackStateModelTest.cpp.o
.PHONY : tests/models/PlaybackStateModelTest.o

# target to build an object file
tests/models/PlaybackStateModelTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/PlaybackStateModelTest.cpp.o
.PHONY : tests/models/PlaybackStateModelTest.cpp.o

tests/models/PlaybackStateModelTest.i: tests/models/PlaybackStateModelTest.cpp.i
.PHONY : tests/models/PlaybackStateModelTest.i

# target to preprocess a source file
tests/models/PlaybackStateModelTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/PlaybackStateModelTest.cpp.i
.PHONY : tests/models/PlaybackStateModelTest.cpp.i

tests/models/PlaybackStateModelTest.s: tests/models/PlaybackStateModelTest.cpp.s
.PHONY : tests/models/PlaybackStateModelTest.s

# target to generate assembly for a file
tests/models/PlaybackStateModelTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/PlaybackStateModelTest.cpp.s
.PHONY : tests/models/PlaybackStateModelTest.cpp.s

tests/models/PlaylistModelTest.o: tests/models/PlaylistModelTest.cpp.o
.PHONY : tests/models/PlaylistModelTest.o

# target to build an object file
tests/models/PlaylistModelTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/PlaylistModelTest.cpp.o
.PHONY : tests/models/PlaylistModelTest.cpp.o

tests/models/PlaylistModelTest.i: tests/models/PlaylistModelTest.cpp.i
.PHONY : tests/models/PlaylistModelTest.i

# target to preprocess a source file
tests/models/PlaylistModelTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/PlaylistModelTest.cpp.i
.PHONY : tests/models/PlaylistModelTest.cpp.i

tests/models/PlaylistModelTest.s: tests/models/PlaylistModelTest.cpp.s
.PHONY : tests/models/PlaylistModelTest.s

# target to generate assembly for a file
tests/models/PlaylistModelTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/PlaylistModelTest.cpp.s
.PHONY : tests/models/PlaylistModelTest.cpp.s

tests/models/QueueModelTest.o: tests/models/QueueModelTest.cpp.o
.PHONY : tests/models/QueueModelTest.o

# target to build an object file
tests/models/QueueModelTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/QueueModelTest.cpp.o
.PHONY : tests/models/QueueModelTest.cpp.o

tests/models/QueueModelTest.i: tests/models/QueueModelTest.cpp.i
.PHONY : tests/models/QueueModelTest.i

# target to preprocess a source file
tests/models/QueueModelTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/QueueModelTest.cpp.i
.PHONY : tests/models/QueueModelTest.cpp.i

tests/models/QueueModelTest.s: tests/models/QueueModelTest.cpp.s
.PHONY : tests/models/QueueModelTest.s

# target to generate assembly for a file
tests/models/QueueModelTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/models/QueueModelTest.cpp.s
.PHONY : tests/models/QueueModelTest.cpp.s

tests/services/AudioPlaybackEngineTest.o: tests/services/AudioPlaybackEngineTest.cpp.o
.PHONY : tests/services/AudioPlaybackEngineTest.o

# target to build an object file
tests/services/AudioPlaybackEngineTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/AudioPlaybackEngineTest.cpp.o
.PHONY : tests/services/AudioPlaybackEngineTest.cpp.o

tests/services/AudioPlaybackEngineTest.i: tests/services/AudioPlaybackEngineTest.cpp.i
.PHONY : tests/services/AudioPlaybackEngineTest.i

# target to preprocess a source file
tests/services/AudioPlaybackEngineTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/AudioPlaybackEngineTest.cpp.i
.PHONY : tests/services/AudioPlaybackEngineTest.cpp.i

tests/services/AudioPlaybackEngineTest.s: tests/services/AudioPlaybackEngineTest.cpp.s
.PHONY : tests/services/AudioPlaybackEngineTest.s

# target to generate assembly for a file
tests/services/AudioPlaybackEngineTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/AudioPlaybackEngineTest.cpp.s
.PHONY : tests/services/AudioPlaybackEngineTest.cpp.s

tests/services/FileScannerTest.o: tests/services/FileScannerTest.cpp.o
.PHONY : tests/services/FileScannerTest.o

# target to build an object file
tests/services/FileScannerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/FileScannerTest.cpp.o
.PHONY : tests/services/FileScannerTest.cpp.o

tests/services/FileScannerTest.i: tests/services/FileScannerTest.cpp.i
.PHONY : tests/services/FileScannerTest.i

# target to preprocess a source file
tests/services/FileScannerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/FileScannerTest.cpp.i
.PHONY : tests/services/FileScannerTest.cpp.i

tests/services/FileScannerTest.s: tests/services/FileScannerTest.cpp.s
.PHONY : tests/services/FileScannerTest.s

# target to generate assembly for a file
tests/services/FileScannerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/FileScannerTest.cpp.s
.PHONY : tests/services/FileScannerTest.cpp.s

tests/services/MetadataReaderTest.o: tests/services/MetadataReaderTest.cpp.o
.PHONY : tests/services/MetadataReaderTest.o

# target to build an object file
tests/services/MetadataReaderTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/MetadataReaderTest.cpp.o
.PHONY : tests/services/MetadataReaderTest.cpp.o

tests/services/MetadataReaderTest.i: tests/services/MetadataReaderTest.cpp.i
.PHONY : tests/services/MetadataReaderTest.i

# target to preprocess a source file
tests/services/MetadataReaderTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/MetadataReaderTest.cpp.i
.PHONY : tests/services/MetadataReaderTest.cpp.i

tests/services/MetadataReaderTest.s: tests/services/MetadataReaderTest.cpp.s
.PHONY : tests/services/MetadataReaderTest.s

# target to generate assembly for a file
tests/services/MetadataReaderTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/MetadataReaderTest.cpp.s
.PHONY : tests/services/MetadataReaderTest.cpp.s

tests/services/SerialCommunicationTest.o: tests/services/SerialCommunicationTest.cpp.o
.PHONY : tests/services/SerialCommunicationTest.o

# target to build an object file
tests/services/SerialCommunicationTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/SerialCommunicationTest.cpp.o
.PHONY : tests/services/SerialCommunicationTest.cpp.o

tests/services/SerialCommunicationTest.i: tests/services/SerialCommunicationTest.cpp.i
.PHONY : tests/services/SerialCommunicationTest.i

# target to preprocess a source file
tests/services/SerialCommunicationTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/SerialCommunicationTest.cpp.i
.PHONY : tests/services/SerialCommunicationTest.cpp.i

tests/services/SerialCommunicationTest.s: tests/services/SerialCommunicationTest.cpp.s
.PHONY : tests/services/SerialCommunicationTest.s

# target to generate assembly for a file
tests/services/SerialCommunicationTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/services/SerialCommunicationTest.cpp.s
.PHONY : tests/services/SerialCommunicationTest.cpp.s

tests/test_main.o: tests/test_main.cpp.o
.PHONY : tests/test_main.o

# target to build an object file
tests/test_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_main.cpp.o
.PHONY : tests/test_main.cpp.o

tests/test_main.i: tests/test_main.cpp.i
.PHONY : tests/test_main.i

# target to preprocess a source file
tests/test_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_main.cpp.i
.PHONY : tests/test_main.cpp.i

tests/test_main.s: tests/test_main.cpp.s
.PHONY : tests/test_main.s

# target to generate assembly for a file
tests/test_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RunTests.dir/build.make CMakeFiles/RunTests.dir/tests/test_main.cpp.s
.PHONY : tests/test_main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... coverage"
	@echo "... MediaPlayerApp"
	@echo "... RunTests"
	@echo "... src/config/AppConfig.o"
	@echo "... src/config/AppConfig.i"
	@echo "... src/config/AppConfig.s"
	@echo "... src/controllers/HardwareController.o"
	@echo "... src/controllers/HardwareController.i"
	@echo "... src/controllers/HardwareController.s"
	@echo "... src/controllers/LibraryController.o"
	@echo "... src/controllers/LibraryController.i"
	@echo "... src/controllers/LibraryController.s"
	@echo "... src/controllers/MainController.o"
	@echo "... src/controllers/MainController.i"
	@echo "... src/controllers/MainController.s"
	@echo "... src/controllers/PlaybackController.o"
	@echo "... src/controllers/PlaybackController.i"
	@echo "... src/controllers/PlaybackController.s"
	@echo "... src/controllers/PlaylistController.o"
	@echo "... src/controllers/PlaylistController.i"
	@echo "... src/controllers/PlaylistController.s"
	@echo "... src/controllers/QueueController.o"
	@echo "... src/controllers/QueueController.i"
	@echo "... src/controllers/QueueController.s"
	@echo "... src/controllers/SourceController.o"
	@echo "... src/controllers/SourceController.i"
	@echo "... src/controllers/SourceController.s"
	@echo "... src/core/Application.o"
	@echo "... src/core/Application.i"
	@echo "... src/core/Application.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models/LibraryModel.o"
	@echo "... src/models/LibraryModel.i"
	@echo "... src/models/LibraryModel.s"
	@echo "... src/models/MediaFileModel.o"
	@echo "... src/models/MediaFileModel.i"
	@echo "... src/models/MediaFileModel.s"
	@echo "... src/models/MetadataModel.o"
	@echo "... src/models/MetadataModel.i"
	@echo "... src/models/MetadataModel.s"
	@echo "... src/models/PlaybackStateModel.o"
	@echo "... src/models/PlaybackStateModel.i"
	@echo "... src/models/PlaybackStateModel.s"
	@echo "... src/models/PlaylistModel.o"
	@echo "... src/models/PlaylistModel.i"
	@echo "... src/models/PlaylistModel.s"
	@echo "... src/models/QueueModel.o"
	@echo "... src/models/QueueModel.i"
	@echo "... src/models/QueueModel.s"
	@echo "... src/repositories/HistoryRepository.o"
	@echo "... src/repositories/HistoryRepository.i"
	@echo "... src/repositories/HistoryRepository.s"
	@echo "... src/repositories/LibraryRepository.o"
	@echo "... src/repositories/LibraryRepository.i"
	@echo "... src/repositories/LibraryRepository.s"
	@echo "... src/repositories/PlaylistRepository.o"
	@echo "... src/repositories/PlaylistRepository.i"
	@echo "... src/repositories/PlaylistRepository.s"
	@echo "... src/services/AudioPlaybackEngine.o"
	@echo "... src/services/AudioPlaybackEngine.i"
	@echo "... src/services/AudioPlaybackEngine.s"
	@echo "... src/services/FileScanner.o"
	@echo "... src/services/FileScanner.i"
	@echo "... src/services/FileScanner.s"
	@echo "... src/services/MetadataReader.o"
	@echo "... src/services/MetadataReader.i"
	@echo "... src/services/MetadataReader.s"
	@echo "... src/services/SerialCommunication.o"
	@echo "... src/services/SerialCommunication.i"
	@echo "... src/services/SerialCommunication.s"
	@echo "... src/ui/ImGuiManager.o"
	@echo "... src/ui/ImGuiManager.i"
	@echo "... src/ui/ImGuiManager.s"
	@echo "... src/ui/UIManager.o"
	@echo "... src/ui/UIManager.i"
	@echo "... src/ui/UIManager.s"
	@echo "... src/views/HistoryScreen.o"
	@echo "... src/views/HistoryScreen.i"
	@echo "... src/views/HistoryScreen.s"
	@echo "... src/views/LibraryScreen.o"
	@echo "... src/views/LibraryScreen.i"
	@echo "... src/views/LibraryScreen.s"
	@echo "... src/views/MainScreen.o"
	@echo "... src/views/MainScreen.i"
	@echo "... src/views/MainScreen.s"
	@echo "... src/views/NowPlayingBar.o"
	@echo "... src/views/NowPlayingBar.i"
	@echo "... src/views/NowPlayingBar.s"
	@echo "... src/views/PlaylistScreen.o"
	@echo "... src/views/PlaylistScreen.i"
	@echo "... src/views/PlaylistScreen.s"
	@echo "... src/views/QueuePanel.o"
	@echo "... src/views/QueuePanel.i"
	@echo "... src/views/QueuePanel.s"
	@echo "... src/views/ScanScreen.o"
	@echo "... src/views/ScanScreen.i"
	@echo "... src/views/ScanScreen.s"
	@echo "... tests/controllers/HardwareControllerBufferTest.o"
	@echo "... tests/controllers/HardwareControllerBufferTest.i"
	@echo "... tests/controllers/HardwareControllerBufferTest.s"
	@echo "... tests/controllers/HardwareControllerInvalidTest.o"
	@echo "... tests/controllers/HardwareControllerInvalidTest.i"
	@echo "... tests/controllers/HardwareControllerInvalidTest.s"
	@echo "... tests/controllers/HardwareControllerParseTest.o"
	@echo "... tests/controllers/HardwareControllerParseTest.i"
	@echo "... tests/controllers/HardwareControllerParseTest.s"
	@echo "... tests/controllers/HardwareControllerRefreshTest.o"
	@echo "... tests/controllers/HardwareControllerRefreshTest.i"
	@echo "... tests/controllers/HardwareControllerRefreshTest.s"
	@echo "... tests/controllers/HardwareControllerTest.o"
	@echo "... tests/controllers/HardwareControllerTest.i"
	@echo "... tests/controllers/HardwareControllerTest.s"
	@echo "... tests/controllers/LibraryControllerExtraTest.o"
	@echo "... tests/controllers/LibraryControllerExtraTest.i"
	@echo "... tests/controllers/LibraryControllerExtraTest.s"
	@echo "... tests/controllers/LibraryControllerTest.o"
	@echo "... tests/controllers/LibraryControllerTest.i"
	@echo "... tests/controllers/LibraryControllerTest.s"
	@echo "... tests/controllers/MainControllerTest.o"
	@echo "... tests/controllers/MainControllerTest.i"
	@echo "... tests/controllers/MainControllerTest.s"
	@echo "... tests/controllers/PlaybackControllerAdvancedTest.o"
	@echo "... tests/controllers/PlaybackControllerAdvancedTest.i"
	@echo "... tests/controllers/PlaybackControllerAdvancedTest.s"
	@echo "... tests/controllers/PlaybackControllerEngineTest.o"
	@echo "... tests/controllers/PlaybackControllerEngineTest.i"
	@echo "... tests/controllers/PlaybackControllerEngineTest.s"
	@echo "... tests/controllers/PlaybackControllerNavigationTest.o"
	@echo "... tests/controllers/PlaybackControllerNavigationTest.i"
	@echo "... tests/controllers/PlaybackControllerNavigationTest.s"
	@echo "... tests/controllers/PlaybackControllerTest.o"
	@echo "... tests/controllers/PlaybackControllerTest.i"
	@echo "... tests/controllers/PlaybackControllerTest.s"
	@echo "... tests/controllers/PlaylistControllerTest.o"
	@echo "... tests/controllers/PlaylistControllerTest.i"
	@echo "... tests/controllers/PlaylistControllerTest.s"
	@echo "... tests/controllers/QueueControllerTest.o"
	@echo "... tests/controllers/QueueControllerTest.i"
	@echo "... tests/controllers/QueueControllerTest.s"
	@echo "... tests/controllers/SourceControllerExtraTest.o"
	@echo "... tests/controllers/SourceControllerExtraTest.i"
	@echo "... tests/controllers/SourceControllerExtraTest.s"
	@echo "... tests/controllers/SourceControllerTest.o"
	@echo "... tests/controllers/SourceControllerTest.i"
	@echo "... tests/controllers/SourceControllerTest.s"
	@echo "... tests/models/LibraryModelTest.o"
	@echo "... tests/models/LibraryModelTest.i"
	@echo "... tests/models/LibraryModelTest.s"
	@echo "... tests/models/MediaFileModelTest.o"
	@echo "... tests/models/MediaFileModelTest.i"
	@echo "... tests/models/MediaFileModelTest.s"
	@echo "... tests/models/MetadataModelTest.o"
	@echo "... tests/models/MetadataModelTest.i"
	@echo "... tests/models/MetadataModelTest.s"
	@echo "... tests/models/PlaybackStateModelTest.o"
	@echo "... tests/models/PlaybackStateModelTest.i"
	@echo "... tests/models/PlaybackStateModelTest.s"
	@echo "... tests/models/PlaylistModelTest.o"
	@echo "... tests/models/PlaylistModelTest.i"
	@echo "... tests/models/PlaylistModelTest.s"
	@echo "... tests/models/QueueModelTest.o"
	@echo "... tests/models/QueueModelTest.i"
	@echo "... tests/models/QueueModelTest.s"
	@echo "... tests/services/AudioPlaybackEngineTest.o"
	@echo "... tests/services/AudioPlaybackEngineTest.i"
	@echo "... tests/services/AudioPlaybackEngineTest.s"
	@echo "... tests/services/FileScannerTest.o"
	@echo "... tests/services/FileScannerTest.i"
	@echo "... tests/services/FileScannerTest.s"
	@echo "... tests/services/MetadataReaderTest.o"
	@echo "... tests/services/MetadataReaderTest.i"
	@echo "... tests/services/MetadataReaderTest.s"
	@echo "... tests/services/SerialCommunicationTest.o"
	@echo "... tests/services/SerialCommunicationTest.i"
	@echo "... tests/services/SerialCommunicationTest.s"
	@echo "... tests/test_main.o"
	@echo "... tests/test_main.i"
	@echo "... tests/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

